### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by ogmkp** [redxtech/hudstart#4]
Hi, I try to build your project with deno but theres no ../frontend/dist assets.js file like assets.sh asks.

I have this error with deno task build in server/:
error: NotFound: No such file or directory (os error 2), stat '../frontend/dist'

Thanks !

**Comment by redxtech** [comment]
I believe you need to generate the frontend before you can build the backend

**Comment by ogmkp** [comment]
Ok thank you, it works.
So, do you think it's possible to get a working overlay with latest score when a match is in progress ?
Because I have a blank page when I choose a match in progress (with "show completed" unchecked).

**Comment by ogmkp** [comment]
With more testing, I'm noticing that this maybe not be a concern on progressing matches, on the Simple overlay, which I'm using to test RLCS 2024, when I select a completed, unfinished or in-progress matches, the overlay JS crashes randomly: https://www.start.gg/tournament/rlcs-2024-major-1/event/major-1
Maybe it has something to do with the names of the players or their teams or something?

Here's what I get as an error in the Chrome console:

```
queries-6ee9e2dc.js:1 TypeError: Cannot read properties of null (reading 'filter')
    at Proxy.createPlayer (main-dfc656cb.js:1:1716)
    at Proxy.p1 (main-dfc656cb.js:1:2172)
    at Ls.run (queries-6ee9e2dc.js:1:4832)
    at get value (queries-6ee9e2dc.js:1:13086)
    at Object.get [as p1] (queries-6ee9e2dc.js:1:28998)
    at Object.get (queries-6ee9e2dc.js:1:27267)
    at Proxy.l (main-dfc656cb.js:1:2282)
    at Ls.run (queries-6ee9e2dc.js:1:4832)
    at get value (queries-6ee9e2dc.js:1:13086)
    at Object.get [as l] (queries-6ee9e2dc.js:1:28998)
```

Are there any counter indications?

**Comment by ogmkp** [comment]
I observe that in this particular case of the RLCS, when a match is in progress and the score remains at 0 - 0, the overlay works, but as soon as a point is set, the overlay crashes.
In any case, the overlay crashes on all matches ending in points.
In addition, the overlay displays the first player's name instead of the team name.

Same problem recurs with CS2 tournaments.
No problem with SSBU tournaments.

How to find a solution?
